### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [nathangthomas/mod_0_skills#1]
# Checklist/Rubric
#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub
* [x]  Directories are named correctly.
* [x]  Files are named correctly.
* [x]  Files and directories are structured correctly.
* [x]  Initial commit was made.
* [x]  Initial commit was pushed to GitHub.

#### Part II: Top Down Design
* [x]  Larger processes were broken into smaller layers.
* [x]  Changes were added and committed with a properly formatted commit message starting with a verb and a capital letter.
* [x]  Changes were pushed to Github.

#### Part III: Classes in a System
* [x]  Directories and files were named and structured correctly.
* [x]  The attributes chosen for **Class #1** represent states or characteristics.
> For class `Food`, an example of an object for that class would be `Lettuce`. When you think about the attributes, make sure that they are applicable to any object. As an example, your first two attributes, `food_types` and `food_groups` wouldn't apply to `Lettuce`. The others are great. I like to ask, "Can [object] have a / be [attribute]?" 
For example: 
  - "Can lettuce have a weight?" (yes)
  - "Can lettuce have a name?" (yes)
  - "Can lettuce be hot or not?" (yes)
  - "Can lettuce have a food types?" (no/confusing) 
* [x]  The attributes chosen for **Class #2** represent states or characteristics.
> Avoid starting your attribute names with the name of the object. For the `Customer` class, we can change `customer_name` to just `name`, and we can change `customer_frequent_orders` to `frequent_orders`.
> There are a few attributes that belong on an `Order` class rather than a `Customer` class: `time_ordered`, `food_ordered`, `paid`, and `left_for_delivery`. 
* [x]  The attributes chosen for **Class #3** represent states or characteristics.
> I'm a little confused by this class. Think of classes as nouns: `Customer`, `Order`, `Menu_Item`, `Furniture`, etc. 
* [x]  The methods chosen for **Class #1** represent behaviors or actions.
* [x]  The methods chosen for **Class #2** represent behaviors or actions.
> Instead of `deliver_food`, you want a method like `receive_food` (since a customer wouldn't be the one doing the delivering. 
* [x]  The methods chosen for **Class #3** represent behaviors or actions.
> See above comment about Class 3. 
* [x]  Data type (string, integer, boolean, array, hash/object, datetime) were identified for each attribute in all three classes.
* [x]  Individual changes were added and committed separately with a properly formatted commit message.
> It looks like four initial commits were made 🤔Any idea how this happened? Make sure that you only use `Initial commit` one time in any project (the very first commit when you're getting the repository set up). Every other commit should be a phrase representing what you did. For example, a good commit message after you added your Food class would be `Add attributes and methods for Food class`. 
<img width="374" alt="screen shot 2019-02-27 at 11 29 23 am" src="https://user-images.githubusercontent.com/3311609/53517241-01fd1200-3a83-11e9-8174-65f664171fc9.png">

* [x]  Changes were pushed to Github.

**Mod 0 Technical Assessment Results**

* [ ]   Technical Ready
* [x]   Pending
> Next steps: Redo Part III, focusing on asking which attributes and methods are really a part of each class. Make sure that your commit messages reflect what changes you made. 
* [ ]   Not ready

**Comment by nathangthomas** [comment]
Thank you for the feedback Rachel. I have included my takeaways below: 
1. Ask yourself "Can [object] have a / be [attribute]?"
2. Avoid starting attribute names with the name of the object.
3. Think of classes as nouns. 

I think I know what happened with the additional Initial commit. My guess is in my rush I forgot that I had made an Initial commit and made an additional Initial commit once I added text to the file instead of a proper commit message. I definitely get anxious with timed assessments, but nothing I can't work though with repeated exposure. 

Thanks again!

**Comment by rwarbelow** [comment]
@nathangthomas Nice work! Classes, attributes, and methods in Part III look good now. 
- [x] Technical Ready
